namespace RhythmCodex.Attributes
{
    public enum NumericData
    {
        LinearOffset,
        MetricOffset,
        Bpm,
        Stop,
        Column,
        Player,
        Id,
        SourceColumn,
        AnnouncerSound,
        Trigger,
        Rate,
        Volume,
        Panning,
        PlayLevel,
        LoadSound,
        PlaySound,
        JudgeNumber,
        JudgeTiming,
        JudgeSound,
        Phrase,
        SourceCommand,
        SourceData,
        Difficulty
    }
}
